export const NEW_JOB = "NEW_JOB";
export const RECIEVE_JOBS = "RECIEVE_JOBS";

export const ADD_SORT_CRITERIA = "ADD_SORT_CRITERIA";
export const CHANGE_SORT_CRITERIA_PROPERTY = "CHANGE_SORT_CRITERIA_PROPERTY";
export const CHANGE_SORT_CRITERIA_DIRECTION = "CHANGE_SORT_CRITERIA_DIRECTION";
export const MOVE_SORT_CRITERIA = "MOVE_SORT_CRITERIA";
export const REMOVE_SORT_CRITERIA = "REMOVE_SORT_CRITERIA";

export const ADD_FILTER = "ADD_FILTER";
export const CHANGE_FILTER_PROPERTY = "CHANGE_FILTER_PROPERTY";
export const REMOVE_FILTER = "REMOVE_FILTER";

export const ADD_LIST_FILTER_VALUE = "ADD_LIST_FILTER_VALUE";
export const REMOVE_LIST_FILTER_VALUE = "REMOVE_LIST_FILTER_VALUE";
export const TOGGLE_LIST_FILTER_VALUE = "TOGGLE_LIST_FILTER_VALUE";
export const CHANGE_LIST_FILTER_INCLUDE_TYPE = "CHANGE_LIST_FILTER_INCLUDE_TYPE";

export const CHANGE_RANGE_FILTER_VALUE = "CHANGE_RANGE_FILTER_VALUE";