export const RECIEVE_JOBS = "RECIEVE_JOBS";
export const REMOVE_JOBS = "REMOVE_JOBS";

export const ADD_SORT_CRITERIA = "ADD_SORT_CRITERIA";
export const CHANGE_SORT_CRITERIA_PROPERTY = "CHANGE_SORT_CRITERIA_PROPERTY";
export const CHANGE_SORT_CRITERIA_DIRECTION = "CHANGE_SORT_CRITERIA_DIRECTION";
export const MOVE_SORT_CRITERIA = "MOVE_SORT_CRITERIA";
export const REMOVE_SORT_CRITERIA = "REMOVE_SORT_CRITERIA";

export const ADD_FILTER = "ADD_FILTER";
export const CHANGE_FILTER_PROPERTY = "CHANGE_FILTER_PROPERTY";
export const REMOVE_FILTER = "REMOVE_FILTER";

export const ADD_LIST_FILTER_VALUE = "ADD_LIST_FILTER_VALUE";
export const REMOVE_LIST_FILTER_VALUE = "REMOVE_LIST_FILTER_VALUE";
export const TOGGLE_LIST_FILTER_VALUE = "TOGGLE_LIST_FILTER_VALUE";
export const CHANGE_LIST_FILTER_INCLUDE_TYPE = "CHANGE_LIST_FILTER_INCLUDE_TYPE";
export const CHANGE_RANGE_FILTER_VALUE = "CHANGE_RANGE_FILTER_VALUE";
export const CHANGE_STRING_FILTER_VALUE = "CHANGE_STRING_FILTER_VALUE";
export const CHANGE_FILTER_STRING_MATCH_FLAGS = "CHANGE_FILTER_STRING_MATCH_FLAGS";

export const RECIEVE_FILTER_SLOTS = "RECIEVE_FILTER_SLOTS";
export const ADD_FILTER_SLOT = "ADD_FILTER_SLOT";
export const CHANGE_FILTER_SLOT_ADD_TEXT = "CHANGE_FILTER_SLOT_ADD_TEXT";
export const CHANGE_FILTER_SLOT = "CHANGE_FILTER_SLOT";
export const RENAME_FILTER_SLOT = "RENAME_FILTER_SLOT";
export const REMOVE_FILTER_SLOT = "REMOVE_FILTER_SLOT";
export const SAVING_FILTER_SLOT = "SAVING_FILTER_SLOT";
export const SAVED_FILTER_SLOT = "SAVED_FILTER_SLOT";

export const RECIEVE_SORT_CRITERIA_SLOTS = "RECIEVE_SORT_CRITERIA_SLOTS";
export const ADD_SORT_CRITERIA_SLOT = "ADD_SORT_CRITERIA_SLOT";
export const CHANGE_SORT_CRITERIA_SLOT_ADD_TEXT = "CHANGE_SORT_CRITERIA_SLOT_ADD_TEXT";
export const CHANGE_SORT_CRITERIA_SLOT = "CHANGE_SORT_CRITERIA_SLOT";
export const RENAME_SORT_CRITERIA_SLOT = "RENAME_SORT_CRITERIA_SLOT";
export const REMOVE_SORT_CRITERIA_SLOT = "REMOVE_SORT_CRITERIA_SLOT";
export const SAVING_SORT_CRITERIA_SLOT = "SAVING_SORT_CRITERIA_SLOT";
export const SAVED_SORT_CRITERIA_SLOT = "SAVED_SORT_CRITERIA_SLOT";